### ISSUE TITLE
Access Violation when injecting Indicium-Supra.dll

### ISSUE THREAD

**Issue by princevv** [nefarius/Indicium-Supra#2]
I am getting this error when attempting to inject the primary DLL. 
Access Violation at 00007FFF6F039885

Do you know where this problem could be stemming from? 
I have no compile errors and everything seems to compile file,
am I missing a lib or something?

**Comment by zigutt** [comment]
Same issue, builded successfully, tried to inject different ways, cant hook Demo App

**Comment by mikeyhalla** [comment]
I had same issue at first but it is because I run my games as admin. Once I ran my injector as admin, all was fine. o7

**Comment by nefarius** [comment]
Sorry, I overlooked this issue.

A few critical things: make sure the process architecture and the DLL match so no x86 injection into x64 and vice versa. The injection also has to take place at the same permission level so no injection into administration processes from a lower privileged session like mentioned before. 

If you have an example Game I happen to own I could try to replicate the issue. Other than that I'm not aware of a bug at launch currently.

**Comment by lufthavn** [comment]
I have the same issue, of games crashing with an 0xc0000005 exception code immediately after injection. So far they have all been Unity games, and I've made sure both architecture match between the game and Indicium-Supra dll, and that the permission levels are identical between the injecting process and the game process. I have tried with the included ImGui sample.

I had it working in an Unreal Engine game for a hot second, but it crashed with the same exception code immediately after showing the overlay. However, that might just be because of the game in question can be unstable at times.

Working with this kind of stuff is not my expertise, I'm probably missing something obvious. 🙂 
I'm on Windows 10 64-bit, and compiled the source with VS 2017.

**Comment by nefarius** [comment]
How does it behave without any plugin being present at all?

**Comment by lufthavn** [comment]
If I delete all the plugin dlls from the directory, it fails in the same way as before.

**Comment by nefarius** [comment]
Well.... can you debug it? Because that's not much of a basis to work on and give support.

**Comment by lufthavn** [comment]
Thank you for the help and patience. 😄 
I attached my Visual Studio debugger to the game process and ran the injector. It did not hit the breakpoint I had in dllmain, but instead stopped in the Poco file Mutex_WIN32.h

![image](https://user-images.githubusercontent.com/7838029/38782031-eaf87610-40ed-11e8-9753-c0df99ef82ee.png)

When I hit Continue, the game process stops. It seems like this might be the cause, but I'm not sure? Again, this is kind of unexplored territory for me, so I'm not even sure if I'm doing it right. 🙂 
I appreciate the help.

**Comment by lufthavn** [comment]
@nefarius gladly! I'm afraid tonight isn't possible for me, but I'll join your Discord as soon as I can, and then we can take it from there when possible? :smiley:

**Comment by nefarius** [comment]
When I'm out im usually online via phone. You find the invite link on my website linked here as well.
